model:
  n_iterations: 100
  shuffle: 1
  batch_size: 32

optimizer:
  learning_rate: 0.001
  clip_norm: 0
  clip_val: 0
  mu_g: 0.0
  n_most_rep: 100
  name: "sgd"

executor:
  strategy: "mw"
  scenario: 1
  remap: 1
  quantize: 0
  comm_period: 10
  aggregate_mode: 1
  delta_switch: 0.0004
  timeout: 15
  send_gradients: 0
  shared_folder: "data/"