model:
  n_workers: 7
  n_iterations: 400
  learning_rate: 0.99
  strategy: "mw"
  scenario: 1
  remap: 1
  quantize: 0
  n_most_rep: 100
  comm_period: 1
  clip_norm: 0
  clip_val: 0
  mu_g: 0.0
  delta_switch: 0.0004
  shuffle: 1
  timeout: 15
  send_gradients: 0