model:
  n_iterations: 400
  shuffle: 1

optimizer:
  learning_rate: 0.99
  clip_norm: 0
  clip_val: 0
  mu_g: 0.0
  n_most_rep: 100

executor:
  strategy: "mw"
  scenario: 1
  remap: 1
  quantize: 1
  comm_period: 10
  delta_switch: 0.0004
  timeout: 15
  send_gradients: 1
  shared_folder: "data/"