model_type: [logistic, nn1]
mode: [0] # 0: Normal, 1: dynamic comms svd, 2: dynamic comms loss Run all 2s again
aggregate_mode: [1] # 0: Avg, 1: Weighted avg, 2: Weighted by loss, 3: Weight by svd
interval: [1]
data_name: [mnist, fashion-mnist]
noniid: [0, 1]
unbalanced: [0, 1]